from fastapi import FastAPI, HTTPException, UploadFile, File
from pydantic import BaseModel
from supabase import create_client, Client
from dotenv import load_dotenv
import os
import math
import uuid
from fastapi.middleware.cors import CORSMiddleware
from ai_engine import analyze_video
import json
import random
import resend 
from report_generator import generate_pdf # <--- We use the imported one!

# 1. Load Secrets
load_dotenv()
url = os.environ.get("SUPABASE_URL")
key = os.environ.get("SUPABASE_KEY")
resend.api_key = os.environ.get("RESEND_API_KEY")

# Global Settings
max_distance = 500  # Meters

# 2. Connect to Supabase
supabase: Client = create_client(url, key)

# 3. Start App
app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Allows ALL frontend to connect
    allow_credentials=True,
    allow_methods=["*"],  # Allows all types of messages (POST, GET, etc.)
    allow_headers=["*"],
)

# --- HELPER: Calculate Distance (Haversine Formula) ---
def calculate_distance(lat1, lon1, lat2, lon2):
    R = 6371000  # Radius of Earth in meters
    phi1 = math.radians(lat1)
    phi2 = math.radians(lat2)
    delta_phi = math.radians(lat2 - lat1)
    delta_lambda = math.radians(lon2 - lon1)

    a = math.sin(delta_phi / 2.0) ** 2 + \
        math.cos(phi1) * math.cos(phi2) * \
        math.sin(delta_lambda / 2.0) ** 2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    return R * c

# --- HELPER: Send Email Notification ---
def send_email_notification(session_id, status, report_url):
    """
    Day 13: Email Trigger
    Sends the final report to the Bank Manager.
    """
    try:
        if not resend.api_key:
            print("⚠️ Skipped Email: No RESEND_API_KEY found.")
            return

        print(f"📧 Sending email for Case {session_id}...")
        
        # Determine subject based on status
        emoji = "✅" if status == "APPROVED" else "❌"
        subject = f"{emoji} Audit Result: {status} (Case: {session_id})"

        html_content = f"""
        <h1>VerifAI Audit Report</h1>
        <p><strong>Case ID:</strong> {session_id}</p>
        <p><strong>Status:</strong> {status}</p>
        <p>The AI Agent has completed the inspection.</p>
        <br>
        <a href="{report_url}" style="background-color: #000; color: #fff; padding: 10px 20px; text-decoration: none; border-radius: 5px;">
            Download Official Certificate
        </a>
        <br><br>
        <p><em>generated by VerifAI Autonomous Auditor</em></p>
        """

        # REPLACE WITH YOUR ACTUAL EMAIL TO TEST
        r = resend.Emails.send({
            "from": "onboarding@resend.dev", 
            "to": "sajjadchaus01@gmail.com", 
            "subject": subject,
            "html": html_content
        })
        print(f"Email Sent: {r}")

    except Exception as e:
        print(f"Email Failed: {e}")

# --- DATA MODELS ---
class CreateInspection(BaseModel):
    case_id: str
    exporter_name: str
    target_lat: float
    target_long: float
    product_type: str = "General Goods" # Default if not provided

class LocationCheck(BaseModel):
    lat: float
    long: float
    case_id: str

# --- API ENDPOINTS ---

@app.get("/")
def home():
    return {"message": "VerifAI API is Online"}

@app.post("/create-inspection")
def create_inspection(data: CreateInspection):
    """
    Step 0: Bank Manager defines the inspection parameters.
    """
    try:
        # Check if case exists
        existing = supabase.table("inspections").select("*").eq("case_id", data.case_id).execute()
        if existing.data:
            raise HTTPException(status_code=400, detail="Case ID already exists")

        # Insert the job with the TARGET location and PRODUCT type
        supabase.table("inspections").insert({
            "case_id": data.case_id,
            "exporter_name": data.exporter_name,
            "target_lat": data.target_lat,
            "target_long": data.target_long,
            "product_type": data.product_type,
            "status": "pending"
        }).execute()
        
        return {"message": "Inspection Created", "case_id": data.case_id}
    except Exception as e:
        print(f"Error: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/initiate-session")
def initiate_session(data: LocationCheck):
    """
    Step 1: Check if User is at the CORRECT Warehouse for THIS Case.
    """
    # Fetch the Target Location for THIS specific case
    session_data = supabase.table("inspections").select("*").eq("case_id", data.case_id).execute()
    
    if not session_data.data:
        raise HTTPException(status_code=404, detail="Case ID not found. Ask Admin to create it first.")
    
    row = session_data.data[0]
    target_lat = row.get("target_lat")
    target_long = row.get("target_long")
    exporter = row.get("exporter_name")

    # Safety check
    if target_lat is None or target_long is None:
         raise HTTPException(status_code=400, detail="This case has no target location set.")

    # Calculate Distance dynamically
    dist = calculate_distance(data.lat, data.long, target_lat, target_long)
    print(f"User is {dist:.2f} meters away from {exporter} warehouse.")

    if dist > max_distance:
        return {"allowed": False, "reason": f"You are {dist:.0f}m away from {exporter}'s location!"}
    
    # Generate OTP
    otp_code = str(random.randint(1000, 9999))
    
    try:
        # Update session with User's ACTUAL location and OTP
        supabase.table("inspections").update({
            "gps_lat": data.lat,
            "gps_long": data.long,
            "verification_code": otp_code,
            "status": "processing" # Optional: Mark as started
        }).eq("case_id", data.case_id).execute()
        
        return {
            "allowed": True, 
            "session_id": data.case_id, 
            "verification_code": otp_code,
            "exporter_name": exporter 
        }
    except Exception as e:
        print(f"DB Error: {e}")
        raise HTTPException(status_code=500, detail="Database Error")
        
@app.post("/upload-video/{session_id}")
async def upload_video(session_id: str, file: UploadFile = File(...)):
    """
    Step 2: Upload Video -> Run AI Analysis -> Generate PDF -> Send Email
    """
    try:
        # --- A. Upload to Supabase Storage ---
        file_content = await file.read()
        file_ext = file.filename.split(".")[-1]
        file_name = f"{session_id}_{uuid.uuid4()}.{file_ext}"

        # Upload Video
        supabase.storage.from_("Videos").upload(
            path=file_name,
            file=file_content,
            file_options={"content-type": file.content_type}
        )
        
        # Get Public URL
        public_url = supabase.storage.from_("Videos").get_public_url(file_name)
        print(f"Video Uploaded: {public_url}")

        # --- B. UPDATE DB: Status -> "processing" ---
        supabase.table("inspections").update({
            "video_url": public_url,
            "status": "processing"
        }).eq("case_id", session_id).execute()

        # --- C. FETCH INSPECTION DATA ---
        session_data = supabase.table("inspections").select("*").eq("case_id", session_id).execute()
        
        if not session_data.data:
            raise HTTPException(status_code=404, detail="Session not found")
        
        row = session_data.data[0]
        expected_code = row.get("verification_code", "0000")
        lat = row.get("gps_lat", 0.0) 
        long = row.get("gps_long", 0.0)
        product_type = row.get("product_type", "General Goods")
        exporter_name = row.get("exporter_name", "Unknown Exporter")

        # --- D. TRIGGER AI ANALYSIS ---
        print(f"AI Verifying {product_type} (Expected Code: {expected_code})...")
        
        ai_result_json_str = analyze_video(public_url, expected_code, product_type)
        
        try:
            ai_data = json.loads(ai_result_json_str)
        except:
            ai_data = {"raw": ai_result_json_str}

        # --- E. SAVE VERDICT TO DB ---
        supabase.table("inspections").update({
            "status": "completed",
            "ai_result": ai_data
        }).eq("case_id", session_id).execute()

        # --- F. GENERATE & UPLOAD PDF REPORT ---
        report_url = None
        try:
            print("Generating PDF Report...")
            # Use the imported function (pass all dynamic data!)
            pdf_filename = generate_pdf(session_id, ai_data, lat, long, exporter_name)
            
            with open(pdf_filename, "rb") as f:
                supabase.storage.from_("Reports").upload(
                    path=pdf_filename,
                    file=f,
                    file_options={"content-type": "application/pdf"}
                )
            
            report_url = supabase.storage.from_("Reports").get_public_url(pdf_filename)
            
            supabase.table("inspections").update({
                "report_url": report_url
            }).eq("case_id", session_id).execute()
            
            if os.path.exists(pdf_filename):
                os.remove(pdf_filename)
            
            print(f"Report Generated: {report_url}")

        except Exception as e:
            print(f"WARNING: Report Generation Failed: {e}")

        # --- H. SEND EMAIL NOTIFICATION ---
        status_str = ai_data.get("verification_status", "COMPLETED")
        send_email_notification(session_id, status_str, report_url)

        # --- G. RETURN FINAL RESPONSE ---
        return {
            "status": "success", 
            "video_url": public_url, 
            "ai_verdict": ai_data,
            "report_url": report_url 
        }

    except Exception as e:
        print(f"Upload Error: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/admin/inspections")
def get_all_inspections():
    """
    Fetches all inspections to show in the Admin Panel.
    """
    try:
        response = supabase.table("inspections").select("*").order("created_at", desc=True).execute()
        return response.data
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/admin/force-verify/{session_id}")
def force_verify_inspection(session_id: str):
    """
    SAFETY NET: Manual Override Button
    """
    print(f"MANUAL OVERRIDE TRIGGERED FOR: {session_id}")
    
    # Create a Fake "Perfect" AI Verdict
    fake_success_data = {
        "verification_status": "APPROVED",
        "liveness_check": {
            "code_spoken_correctly": True,
            "detected_code_transcript": "User spoke code clearly (Manual Override)",
            "voice_liveness_confidence": "HIGH"
        },
        "stock_assessment": {
            "is_warehouse_environment": True,
            "inventory_visible": True,
            "inventory_description": "Verified commercial stock via Manual Audit Override.",
            "commercial_volume_detected": True
        },
        "risk_assessment": {
            "fraud_flags_detected": [],
            "overall_confidence_score": 100
        },
        "auditor_reasoning": "MANUAL OVERRIDE: Verified by Senior Auditor during review."
    }

    try:
        # Update Database
        supabase.table("inspections").update({
            "status": "completed",
            "ai_result": fake_success_data
        }).eq("case_id", session_id).execute()

        # Regenerate PDF (We need generic lat/long here or fetch from DB)
        # Fetching actual DB data is safer to keep map accurate
        session_data = supabase.table("inspections").select("*").eq("case_id", session_id).execute()
        lat = 0.0
        long = 0.0
        exporter_name = "Unknown"
        if session_data.data:
             lat = session_data.data[0].get("gps_lat", 0.0)
             long = session_data.data[0].get("gps_long", 0.0)
             exporter_name = session_data.data[0].get("exporter_name", "Unknown")

        pdf_filename = generate_pdf(session_id, fake_success_data, lat, long, exporter_name)
        
        with open(pdf_filename, "rb") as f:
            supabase.storage.from_("Reports").upload(
                path=pdf_filename,
                file=f,
                file_options={"content-type": "application/pdf", "upsert": "true"}
            )
        
        report_url = supabase.storage.from_("Reports").get_public_url(pdf_filename)
        
        supabase.table("inspections").update({
            "report_url": report_url
        }).eq("case_id", session_id).execute()

        if os.path.exists(pdf_filename):
            os.remove(pdf_filename)

        # SEND EMAIL
        send_email_notification(session_id, "APPROVED", report_url)

        return {"status": "success", "message": "Manual Override Applied.", "report_url": report_url}

    except Exception as e:
        print(f"Override Failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))