from fastapi import FastAPI, HTTPException, UploadFile, File
from pydantic import BaseModel
from supabase import create_client, Client
from dotenv import load_dotenv
import os
import math
import uuid
from fastapi.middleware.cors import CORSMiddleware
from ai_engine import analyze_video
import json
import random
import resend 
from report_generator import generate_pdf # <--- We use the imported one!

# 1. Load Secrets
load_dotenv()
url = os.environ.get("SUPABASE_URL")
key = os.environ.get("SUPABASE_KEY")
resend.api_key = os.environ.get("RESEND_API_KEY")

# Global Settings
max_distance = 500  # Meters

# 2. Connect to Supabase
supabase: Client = create_client(url, key)

# 3. Start App
app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Allows ALL frontend to connect
    allow_credentials=True,
    allow_methods=["*"],  # Allows all types of messages (POST, GET, etc.)
    allow_headers=["*"],
)

# --- HELPER: Verify Admin (Supabase Auth) ---
def verify_admin(authorization: str = Header(None)):
    """
    Protects Admin Routes. 
    Frontend must send header: 'Authorization: Bearer <access_token>'
    """
    if not authorization:
        raise HTTPException(status_code=401, detail="Missing Token")
    
    try:
        token = authorization.replace("Bearer ", "")
        # Ask Supabase: "Is this token valid?"
        user = supabase.auth.get_user(token)
        if not user:
             raise HTTPException(status_code=401, detail="Invalid Token")
        return user
    except Exception as e:
        raise HTTPException(status_code=401, detail="Session Expired. Please Login Again.")

# --- HELPER: Calculate Distance ---
def calculate_distance(lat1, lon1, lat2, lon2):
    R = 6371000 
    phi1 = math.radians(lat1)
    phi2 = math.radians(lat2)
    delta_phi = math.radians(lat2 - lat1)
    delta_lambda = math.radians(lon2 - lon1)

    a = math.sin(delta_phi / 2.0) ** 2 + \
        math.cos(phi1) * math.cos(phi2) * \
        math.sin(delta_lambda / 2.0) ** 2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    return R * c

# --- HELPER: Send Email Notification ---
def send_email_notification(session_id, status, report_url, recipient_email):
    """
    Sends the final report to the Client's Email.
    """
    try:
        if not resend.api_key:
            print("⚠️ Skipped Email: No RESEND_API_KEY found.")
            return

        print(f"📧 Sending email to {recipient_email}...")
        
        emoji = "✅" if status == "APPROVED" else "❌"
        subject = f"{emoji} Audit Result: {status} (Case: {session_id})"

        html_content = f"""
        <h1>VerifAI Audit Report</h1>
        <p><strong>Case ID:</strong> {session_id}</p>
        <p><strong>Status:</strong> {status}</p>
        <br>
        <a href="{report_url}" style="background-color: #000; color: #fff; padding: 10px 20px; text-decoration: none; border-radius: 5px;">
            Download Certificate
        </a>
        <br><br>
        <p><em>generated by VerifAI Autonomous Auditor</em></p>
        """

        r = resend.Emails.send({
            "from": "onboarding@resend.dev", 
            "to": recipient_email, # Dynamic Email!
            "subject": subject,
            "html": html_content
        })
        print(f"Email Sent: {r}")

    except Exception as e:
        print(f"Email Failed: {e}")

# --- DATA MODELS ---
class CreateInspection(BaseModel):
    case_id: str
    exporter_name: str
    client_email: str  # <--- NEW: Who gets the email?
    target_lat: float
    target_long: float
    product_type: str = "General Goods"

class LocationCheck(BaseModel):
    lat: float
    long: float
    case_id: str

# --- API ENDPOINTS ---

@app.get("/")
def home():
    return {"message": "VerifAI API is Online"}

# 1. PROTECTED: Admin Login Required to Create Jobs
@app.post("/create-inspection")
def create_inspection(data: CreateInspection, user = Depends(verify_admin)):
    """
    Only Admins can create new inspection jobs.
    """
    try:
        existing = supabase.table("inspections").select("*").eq("case_id", data.case_id).execute()
        if existing.data:
            raise HTTPException(status_code=400, detail="Case ID already exists")

        supabase.table("inspections").insert({
            "case_id": data.case_id,
            "exporter_name": data.exporter_name,
            "client_email": data.client_email, # Save the email
            "target_lat": data.target_lat,
            "target_long": data.target_long,
            "product_type": data.product_type,
            "status": "pending"
        }).execute()
        
        return {"message": "Inspection Created", "case_id": data.case_id}
    except Exception as e:
        print(f"Error: {e}")
        raise HTTPException(status_code=500, detail=str(e))

# 2. PUBLIC: The Exporter uses this (No Login Required)
@app.post("/initiate-session")
def initiate_session(data: LocationCheck):
    # Fetch Target Location
    session_data = supabase.table("inspections").select("*").eq("case_id", data.case_id).execute()
    
    if not session_data.data:
        raise HTTPException(status_code=404, detail="Case ID not found.")
    
    row = session_data.data[0]
    target_lat = row.get("target_lat")
    target_long = row.get("target_long")
    exporter = row.get("exporter_name")

    if target_lat is None or target_long is None:
         raise HTTPException(status_code=400, detail="Target location missing.")

    # Distance Check
    dist = calculate_distance(data.lat, data.long, target_lat, target_long)
    print(f"User is {dist:.2f} meters away.")

    if dist > max_distance:
        return {"allowed": False, "reason": f"You are {dist:.0f}m away from location!"}
    
    otp_code = str(random.randint(1000, 9999))
    
    try:
        supabase.table("inspections").update({
            "gps_lat": data.lat,
            "gps_long": data.long,
            "verification_code": otp_code,
            "status": "processing"
        }).eq("case_id", data.case_id).execute()
        
        return {
            "allowed": True, 
            "session_id": data.case_id, 
            "verification_code": otp_code,
            "exporter_name": exporter 
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail="Database Error")

# 3. PUBLIC: Video Upload
@app.post("/upload-video/{session_id}")
async def upload_video(session_id: str, file: UploadFile = File(...)):
    try:
        # A. Upload
        file_content = await file.read()
        file_ext = file.filename.split(".")[-1]
        file_name = f"{session_id}_{uuid.uuid4()}.{file_ext}"

        supabase.storage.from_("Videos").upload(file_name, file_content, {"content-type": file.content_type})
        public_url = supabase.storage.from_("Videos").get_public_url(file_name)

        supabase.table("inspections").update({"video_url": public_url, "status": "processing"}).eq("case_id", session_id).execute()

        # B. Fetch Data
        session_data = supabase.table("inspections").select("*").eq("case_id", session_id).execute()
        if not session_data.data: raise HTTPException(status_code=404)
        
        row = session_data.data[0]
        expected_code = row.get("verification_code", "0000")
        client_email = row.get("client_email", "sajjadchaus01@gmail.com") # <--- Dynamic Email
        lat = row.get("gps_lat", 0.0)
        long = row.get("gps_long", 0.0)
        product_type = row.get("product_type", "General Goods")
        exporter_name = row.get("exporter_name", "Unknown")

        # C. AI Analysis
        ai_result_json_str = analyze_video(public_url, expected_code, product_type)
        try: ai_data = json.loads(ai_result_json_str)
        except: ai_data = {"raw": ai_result_json_str}

        supabase.table("inspections").update({"status": "completed", "ai_result": ai_data}).eq("case_id", session_id).execute()

        # D. Generate PDF
        report_url = None
        try:
            pdf_filename = generate_pdf(session_id, ai_data, lat, long, exporter_name)
            with open(pdf_filename, "rb") as f:
                supabase.storage.from_("Reports").upload(pdf_filename, f, {"content-type": "application/pdf"})
            
            report_url = supabase.storage.from_("Reports").get_public_url(pdf_filename)
            supabase.table("inspections").update({"report_url": report_url}).eq("case_id", session_id).execute()
            if os.path.exists(pdf_filename): os.remove(pdf_filename)
        except Exception as e:
            print(f"PDF Error: {e}")

        # E. Send Email
        status_str = ai_data.get("verification_status", "COMPLETED")
        send_email_notification(session_id, status_str, report_url, client_email)

        return {"status": "success", "ai_verdict": ai_data, "report_url": report_url}

    except Exception as e:
        print(f"Error: {e}")
        raise HTTPException(status_code=500, detail=str(e))



# 4. PROTECTED: Admin Dashboard
@app.get("/admin/inspections")
def get_all_inspections(user = Depends(verify_admin)): # <--- Added Protection
    """
    Shows all audits. Only for Logged-in Admins.
    """
    try:
        response = supabase.table("inspections").select("*").order("created_at", desc=True).execute()
        return response.data
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# 5. PROTECTED: Manual Override
@app.post("/admin/force-verify/{session_id}")
def force_verify_inspection(session_id: str, user = Depends(verify_admin)): # <--- Added Protection
    """
    SAFETY NET: Manual Override Button
    """
    print(f"MANUAL OVERRIDE TRIGGERED FOR: {session_id}")
    
    # Create a Fake "Perfect" AI Verdict
    fake_success_data = {
        "verification_status": "APPROVED",
        "liveness_check": {
            "code_spoken_correctly": True,
            "detected_code_transcript": "User spoke code clearly (Manual Override)",
            "voice_liveness_confidence": "HIGH"
        },
        "stock_assessment": {
            "is_warehouse_environment": True,
            "inventory_visible": True,
            "inventory_description": "Verified commercial stock via Manual Audit Override.",
            "commercial_volume_detected": True
        },
        "risk_assessment": {
            "fraud_flags_detected": [],
            "overall_confidence_score": 100
        },
        "auditor_reasoning": "MANUAL OVERRIDE: Verified by Senior Auditor during review."
    }

    try:
        # Update Database
        supabase.table("inspections").update({
            "status": "completed",
            "ai_result": fake_success_data
        }).eq("case_id", session_id).execute()

        # Regenerate PDF (Fetching actual DB data to keep map accurate)
        session_data = supabase.table("inspections").select("*").eq("case_id", session_id).execute()
        
        # Defaults
        lat = 0.0
        long = 0.0
        exporter_name = "Unknown"
        client_email = "admin@verifai.com" # Default if missing

        if session_data.data:
             row = session_data.data[0]
             lat = row.get("gps_lat", 0.0)
             long = row.get("gps_long", 0.0)
             exporter_name = row.get("exporter_name", "Unknown")
             client_email = row.get("client_email", "admin@verifai.com") # <--- Fetch Email

        pdf_filename = generate_pdf(session_id, fake_success_data, lat, long, exporter_name)
        
        with open(pdf_filename, "rb") as f:
            supabase.storage.from_("Reports").upload(
                path=pdf_filename,
                file=f,
                file_options={"content-type": "application/pdf", "upsert": "true"}
            )
        
        report_url = supabase.storage.from_("Reports").get_public_url(pdf_filename)
        
        supabase.table("inspections").update({
            "report_url": report_url
        }).eq("case_id", session_id).execute()

        if os.path.exists(pdf_filename):
            os.remove(pdf_filename)

        # SEND EMAIL (FIXED: Added client_email)
        send_email_notification(session_id, "APPROVED", report_url, client_email)

        return {"status": "success", "message": "Manual Override Applied.", "report_url": report_url}

    except Exception as e:
        print(f"Override Failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))