from fpdf import FPDF
from datetime import datetime
import json
import os

class PDF(FPDF):
    def header(self):
        # Logo / Title
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'VerifAI | Autonomous Stock Audit', 0, 1, 'L')
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, 'Bank-Grade Pre-Shipment Inspection Certificate', 0, 1, 'L')
        self.ln(5)
        # Line break
        self.set_draw_color(0, 0, 0)
        self.line(10, 30, 200, 30)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Page {self.page_no()} - Generated by VerifAI Engine', 0, 0, 'C')

# The built-in PDF fonts only support Latin-1 characters, and fpdf2 raises an error on anything else.
# Swap common typographic characters for plain ones, and replace any others with "?".
PLAIN_CHARACTERS = {"—": "-", "–": "-", "‘": "'", "’": "'", "“": '"', "”": '"', "…": "...", "•": "-", "₹": "Rs."}

def to_latin1(value):
    """Return value with every string in it made safe for the built-in PDF fonts."""
    if isinstance(value, dict):
        return {key: to_latin1(item) for key, item in value.items()}
    if isinstance(value, list):
        return [to_latin1(item) for item in value]
    if isinstance(value, str):
        for fancy, plain in PLAIN_CHARACTERS.items():
            value = value.replace(fancy, plain)
        return value.encode("latin-1", "replace").decode("latin-1")
    return value

def generate_pdf(case_id, ai_data, lat=0.0, long=0.0, exporter_name="Unknown Exporter"):
    """
    Generates a professional PDF report with Map links, Exporter Name, and Status Box.
    """
    # Safety Check: Ensure ai_data is a dictionary
    if isinstance(ai_data, str):
        try:
            ai_data = json.loads(ai_data)
        except:
            ai_data = {}

    # AI text and names can contain characters the PDF fonts can't draw
    ai_data = to_latin1(ai_data)
    exporter_name = to_latin1(exporter_name)

    pdf = PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # 1. REPORT METADATA
    pdf.set_font("Arial", "B", 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, f"INSPECTION ID: {to_latin1(case_id)}", 0, 1)
    
    # Exporter Name (Dynamic!)
    pdf.cell(0, 6, f"EXPORTER: {exporter_name}", 0, 1)

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    pdf.set_font("Arial", "", 10)
    pdf.cell(0, 6, f"Date & Time: {timestamp}", 0, 1)
    
    # GPS Location
    pdf.cell(0, 6, f"GPS Location: {lat}, {long}", 0, 1)
    
    # We use the standard Google Maps Search URL
    map_url = f"https://www.google.com/maps?q={lat},{long}"
    
    pdf.set_text_color(0, 0, 255) # Blue Link
    pdf.set_font("Arial", "U", 10) # Underline
    pdf.cell(0, 6, "View Location on Google Maps (Click Here)", 0, 1, link=map_url)
    pdf.set_text_color(0, 0, 0) # Reset color
    pdf.ln(10)

    

    # 2. THE VERDICT (Big Colored Box)
    status = ai_data.get("verification_status", "UNKNOWN").upper()
    
    pdf.set_font("Arial", "B", 14)
    if status == "APPROVED":
        pdf.set_fill_color(220, 255, 220)  # Light Green
        pdf.set_text_color(0, 100, 0)      # Dark Green
        box_text = "  VERDICT: APPROVED (SAFE TO FINANCE)  "
    else:
        pdf.set_fill_color(255, 220, 220)  # Light Red
        pdf.set_text_color(150, 0, 0)      # Dark Red
        box_text = f"  VERDICT: {status} (HIGH RISK)  "
    
    pdf.cell(0, 15, box_text, 0, 1, 'C', fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(10)

    # 3. LIVENESS CHECK
    pdf.set_font("Arial", "B", 11)
    pdf.cell(0, 8, "SECTION 1: LIVENESS & SECURITY", 0, 1)
    pdf.set_font("Arial", "", 10)
    
    liveness = ai_data.get("liveness_check", {})
    code_check = "PASS" if liveness.get("code_spoken_correctly") else "FAIL"
    
    pdf.cell(30, 8, "Code Check:", 0, 0)
    pdf.set_font("Arial", "B", 10)
    pdf.cell(0, 8, code_check, 0, 1)
    pdf.set_font("Arial", "", 10)
    
    pdf.multi_cell(0, 6, f"Audio Transcript: \"{liveness.get('detected_code_transcript', 'N/A')}\"")
    pdf.ln(5)

    # 4. PRODUCT & STOCK ASSESSMENT
    pdf.set_font("Arial", "B", 11)
    pdf.cell(0, 8, "SECTION 2: PRODUCT & COLLATERAL", 0, 1)
    pdf.set_font("Arial", "", 10)
    
    # Handle both old 'stock_assessment' and new 'product_verification' structures safely
    stock = ai_data.get("stock_assessment", {})
    product_verif = ai_data.get("product_verification", {})

    # Product Match Check
    matches_product = "YES" if product_verif.get("matches_expected_product") else "NO/UNCERTAIN"
    pdf.cell(50, 6, f"Matches Expected Product: {matches_product}", 0, 1)

    description = product_verif.get('visual_description') or stock.get('inventory_description') or "N/A"
    pdf.multi_cell(0, 6, f"Visual Findings: {description}")
    pdf.ln(2)
    
    is_commercial = "YES" if stock.get("commercial_volume_detected") else "NO"
    pdf.cell(50, 6, f"Commercial Volume: {is_commercial}", 0, 1)
    
    condition = stock.get("condition", "N/A")
    pdf.cell(50, 6, f"Stock Condition: {condition}", 0, 1)
    pdf.ln(5)

    # 5. AUDITOR REASONING
    pdf.set_font("Arial", "B", 11)
    pdf.cell(0, 8, "SECTION 3: AI AUDITOR REASONING", 0, 1)
    pdf.set_font("Arial", "I", 10)
    pdf.multi_cell(0, 6, ai_data.get("auditor_reasoning", "No reasoning provided."))
    pdf.ln(10)

    # 6. SIGNATURE
    pdf.set_y(-40)
    pdf.set_font("Arial", "B", 10)
    pdf.cell(0, 5, "Digitally Verified by VerifAI Engine", 0, 1, 'R')
    pdf.set_font("Arial", "", 8)
    pdf.cell(0, 5, f"Report generated automatically. No signature required.", 0, 1, 'R')

    # Save
    filename = f"report_{case_id}.pdf"
    pdf.output(filename)
    return filename